const FOOD_KEY="bb_food", USERS_KEY="bb_users", CART_KEY="bb_cart", ORDERS_KEY="bb_orders", FAV_KEY="bb_favs", REVIEWS_KEY="bb_reviews", SESSION_KEY="bb_session", THEME_KEY="bb_theme", COUPON_KEY="bb_coupon";

const defaultFoods=[
{id:1,name:"Classic Espresso",cat:"Coffee",price:110,rating:4.8,veg:true,popular:true,emoji:"☕",desc:"Bold, rich espresso with a smooth finish.",ingredients:"Arabica espresso, water"},
{id:2,name:"Cappuccino",cat:"Coffee",price:160,rating:4.9,veg:true,popular:true,emoji:"☕",desc:"Velvety espresso topped with creamy foam.",ingredients:"Espresso, steamed milk, milk foam"},
{id:3,name:"Café Latte",cat:"Coffee",price:170,rating:4.8,veg:true,popular:true,emoji:"🥛",desc:"Smooth espresso balanced with silky milk.",ingredients:"Espresso, steamed milk"},
{id:4,name:"Mocha",cat:"Coffee",price:190,rating:4.7,veg:true,popular:false,emoji:"🍫",desc:"Coffee and chocolate finished with creamy foam.",ingredients:"Espresso, chocolate, milk"},
{id:5,name:"Americano",cat:"Coffee",price:130,rating:4.5,veg:true,popular:false,emoji:"☕",desc:"Espresso extended with hot water.",ingredients:"Espresso, hot water"},
{id:6,name:"Caramel Macchiato",cat:"Coffee",price:210,rating:4.9,veg:true,popular:true,emoji:"🍮",desc:"Creamy coffee with vanilla and caramel drizzle.",ingredients:"Espresso, milk, vanilla, caramel"},
{id:7,name:"Cold Coffee",cat:"Cold Beverages",price:180,rating:4.8,veg:true,popular:true,emoji:"🧋",desc:"Chilled, creamy coffee for warm afternoons.",ingredients:"Coffee, milk, ice, sugar"},
{id:8,name:"Iced Latte",cat:"Cold Beverages",price:190,rating:4.6,veg:true,popular:false,emoji:"🧋",desc:"Cold milk and espresso over ice.",ingredients:"Espresso, milk, ice"},
{id:9,name:"Chocolate Frappe",cat:"Cold Beverages",price:220,rating:4.9,veg:true,popular:true,emoji:"🥤",desc:"Chocolatey blended bliss with a creamy finish.",ingredients:"Chocolate, coffee, milk, ice"},
{id:10,name:"Vanilla Frappe",cat:"Cold Beverages",price:210,rating:4.7,veg:true,popular:false,emoji:"🥤",desc:"Vanilla-scented creamy blended coffee.",ingredients:"Coffee, vanilla, milk, ice"},
{id:11,name:"Masala Tea",cat:"Tea",price:90,rating:4.6,veg:true,popular:false,emoji:"🍵",desc:"Aromatic Indian tea with warming spices.",ingredients:"Tea, milk, ginger, cardamom, spices"},
{id:12,name:"Green Tea",cat:"Tea",price:100,rating:4.5,veg:true,popular:false,emoji:"🍵",desc:"Light, refreshing green tea.",ingredients:"Green tea leaves, water"},
{id:13,name:"Lemon Tea",cat:"Tea",price:95,rating:4.4,veg:true,popular:false,emoji:"🍋",desc:"Refreshing tea with a bright lemon finish.",ingredients:"Tea, lemon, honey"},
{id:14,name:"Veg Sandwich",cat:"Snacks",price:150,rating:4.6,veg:true,popular:true,emoji:"🥪",desc:"Fresh vegetables and cheese in toasted bread.",ingredients:"Bread, vegetables, cheese, sauces"},
{id:15,name:"Cheese Sandwich",cat:"Snacks",price:170,rating:4.7,veg:true,popular:false,emoji:"🥪",desc:"Golden toasted sandwich loaded with cheese.",ingredients:"Bread, cheese, butter"},
{id:16,name:"French Fries",cat:"Snacks",price:120,rating:4.5,veg:true,popular:true,emoji:"🍟",desc:"Crispy golden fries with a pinch of seasoning.",ingredients:"Potatoes, oil, seasoning"},
{id:17,name:"Garlic Bread",cat:"Snacks",price:140,rating:4.6,veg:true,popular:false,emoji:"🥖",desc:"Toasted bread with garlic butter and herbs.",ingredients:"Bread, garlic, butter, herbs"},
{id:18,name:"Veg Burger",cat:"Fast Food",price:180,rating:4.6,veg:true,popular:true,emoji:"🍔",desc:"Crispy veggie patty with fresh toppings.",ingredients:"Veg patty, bun, lettuce, tomato, sauce"},
{id:19,name:"Cheese Burger",cat:"Fast Food",price:220,rating:4.7,veg:false,popular:true,emoji:"🍔",desc:"Juicy patty, melted cheese and house sauce.",ingredients:"Patty, bun, cheese, lettuce, sauce"},
{id:20,name:"Margherita Pizza",cat:"Fast Food",price:260,rating:4.8,veg:true,popular:true,emoji:"🍕",desc:"Classic pizza with tomato, mozzarella and basil.",ingredients:"Pizza base, tomato, mozzarella, basil"},
{id:21,name:"Paneer Pizza",cat:"Fast Food",price:290,rating:4.8,veg:true,popular:false,emoji:"🍕",desc:"Creamy paneer and vegetables on a cheesy pizza.",ingredients:"Pizza base, paneer, cheese, vegetables"},
{id:22,name:"Chocolate Cake",cat:"Desserts",price:160,rating:4.9,veg:true,popular:true,emoji:"🍰",desc:"Moist chocolate cake with silky frosting.",ingredients:"Flour, cocoa, chocolate, cream"},
{id:23,name:"Brownie",cat:"Desserts",price:130,rating:4.9,veg:true,popular:true,emoji:"🍫",desc:"Rich fudgy brownie served warm.",ingredients:"Chocolate, cocoa, flour, butter"},
{id:24,name:"Cheesecake",cat:"Desserts",price:190,rating:4.7,veg:true,popular:false,emoji:"🍰",desc:"Creamy cheesecake with a buttery biscuit base.",ingredients:"Cream cheese, biscuit, sugar, cream"},
{id:25,name:"Chocolate Muffin",cat:"Desserts",price:110,rating:4.6,veg:true,popular:false,emoji:"🧁",desc:"Soft chocolate muffin with chocolate chips.",ingredients:"Flour, cocoa, chocolate chips, butter"}
];

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function money(n){return "₹"+Number(n).toFixed(2)}
function toast(msg){let t=$("#toast");if(!t)return;t.textContent=msg;t.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove("show"),2500)}
function foods(){let f=get(FOOD_KEY,null);if(!f){set(FOOD_KEY,defaultFoods);return defaultFoods}return f}
function users(){let u=get(USERS_KEY,null);if(!u){u=[{name:"Demo Customer",email:"customer@beanbliss.com",phone:"9876543210",password:"customer123",role:"customer"}];set(USERS_KEY,u)}return u}
function session(){return get(SESSION_KEY,null)}
function cart(){return get(CART_KEY,[])}
function saveCart(c){set(CART_KEY,c);updateCartCount()}
function updateCartCount(){let n=cart().reduce((a,x)=>a+x.qty,0);$$(".cart-count").forEach(e=>e.textContent=n)}
function currentUser(){return session()}
function setupUserUI(){let p=$("#profileLink"),u=session();if(!p)return;if(u){p.textContent=u.role==="admin"?"Admin":"Hi, "+u.name.split(" ")[0];p.href=u.role==="admin"?"admin.html":"orders.html"}else{p.textContent="Login";p.href="login.html"}}
function setupTheme(){let saved=localStorage.getItem(THEME_KEY);if(saved==="dark")document.body.classList.add("dark");let b=$("#themeBtn");if(b)b.onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem(THEME_KEY,document.body.classList.contains("dark")?"dark":"light");b.textContent=document.body.classList.contains("dark")?"☀":"☾"}}
function setupNav(){let t=$("#menuToggle"),n=$("#mainNav");if(t&&n)t.onclick=()=>n.classList.toggle("open")}
function addToCart(id,qty=1){let f=foods().find(x=>x.id==id);if(!f)return;let c=cart(),item=c.find(x=>x.id==id);if(item)item.qty+=qty;else c.push({id:f.id,qty,price:f.price,name:f.name,emoji:f.emoji});saveCart(c);toast(f.name+" added to cart")}
function toggleFav(id){let f=get(FAV_KEY,[]),i=f.indexOf(Number(id));if(i>=0)f.splice(i,1);else f.push(Number(id));set(FAV_KEY,f);renderMenu();renderFavorites();toast(i>=0?"Removed from favorites":"Added to favorites")}
function productCard(f){let fav=get(FAV_KEY,[]).includes(f.id);return `<article class="product-card"><div class="product-image" data-detail="${f.id}" style="cursor:pointer"><button class="fav-btn ${fav?"active":""}" data-fav="${f.id}" title="Favorite">${fav?"♥":"♡"}</button><span>${f.emoji}</span>${f.veg?'<small>● VEG</small>':''}</div><div class="product-info"><h3>${f.name}</h3><p>${f.desc}</p><div class="product-meta"><div><span class="price">${money(f.price)}</span><div class="rating">★ ${f.rating}</div></div><button class="add-btn" data-add="${f.id}" title="Add to cart">+</button></div></div></article>`}
function bindProductEvents(){ $$("[data-add]").forEach(b=>b.onclick=e=>{e.stopPropagation();addToCart(b.dataset.add)});$$("[data-fav]").forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)});$$("[data-detail]").forEach(e=>e.onclick=()=>showFoodDetail(e.dataset.detail))}
function showFoodDetail(id){let f=foods().find(x=>x.id==id);if(!f)return;let m=$("#modal"),c=$("#modalContent");if(!m||!c)return;c.innerHTML=`<div class="detail-layout"><div class="detail-art">${f.emoji}</div><div class="detail-info"><span class="eyebrow">${f.cat}</span><h2>${f.name}</h2><div class="rating">★ ${f.rating} · ${f.veg?"Vegetarian":"Non-Vegetarian"}</div><p>${f.desc}</p><p><strong>Ingredients:</strong> ${f.ingredients}</p><h2>${money(f.price)}</h2><div class="quantity"><button id="minus">−</button><span id="detailQty">1</span><button id="plus">+</button></div><button class="btn btn-primary full-btn" id="detailAdd">Add to Cart →</button></div></div>`;m.classList.remove("hidden");let q=1;$("#minus").onclick=()=>{q=Math.max(1,q-1);$("#detailQty").textContent=q};$("#plus").onclick=()=>{$("#detailQty").textContent=++q};$("#detailAdd").onclick=()=>{addToCart(f.id,q);m.classList.add("hidden")};$("#modalClose").onclick=()=>m.classList.add("hidden")}
function renderMenu(){let grid=$("#menuGrid");if(!grid)return;let list=foods(),search=($("#searchInput")?.value||"").toLowerCase(),cat=window.selectedCat||"All";if(search)list=list.filter(f=>(f.name+" "+f.desc+" "+f.cat).toLowerCase().includes(search));if(cat!=="All")list=list.filter(f=>f.cat===cat);if($("#vegOnly")?.checked)list=list.filter(f=>f.veg);if($("#popularOnly")?.checked)list=list.filter(f=>f.popular);let sort=$("#sortSelect")?.value;if(sort==="low")list.sort((a,b)=>a.price-b.price);if(sort==="high")list.sort((a,b)=>b.price-a.price);if(sort==="rating")list.sort((a,b)=>b.rating-a.rating);grid.innerHTML=list.length?list.map(productCard).join(""):`<div class="empty-state" style="grid-column:1/-1"><h2>No bliss found.</h2><p>Try another search or category.</p></div>`;bindProductEvents()}
function renderFavorites(){let g=$("#favoritesGrid");if(!g)return;let ids=get(FAV_KEY,[]),list=foods().filter(f=>ids.includes(f.id));g.innerHTML=list.length?list.map(productCard).join(""):`<div class="empty-state" style="grid-column:1/-1"><h3>No favourites yet.</h3><p>Tap the heart on any menu item to save it.</p></div>`;bindProductEvents()}
function initMenu(){let c=$("#categoryFilters");if(!c)return;let cats=["All",...new Set(foods().map(f=>f.cat))];c.innerHTML=cats.map(x=>`<button class="chip ${x==="All"?"active":""}" data-cat="${x}">${x}</button>`).join("");$$("[data-cat]").forEach(b=>b.onclick=()=>{$$("[data-cat]").forEach(x=>x.classList.remove("active"));b.classList.add("active");window.selectedCat=b.dataset.cat;renderMenu()});["searchInput","vegOnly","popularOnly","sortSelect"].forEach(id=>$( "#"+id)?.addEventListener("input",renderMenu));renderMenu();renderFavorites();$("#modalClose")?.addEventListener("click",()=>$("#modal").classList.add("hidden"))}
function renderFeatured(){let g=$("#featuredGrid");if(g){g.innerHTML=foods().filter(f=>f.popular).slice(0,4).map(productCard).join("");bindProductEvents()}}
function totals(){let c=cart(),sub=c.reduce((a,x)=>a+x.price*x.qty,0),coupon=get(COUPON_KEY,null),discount=0;if(coupon){if(coupon==="BEAN10")discount=sub*.10;if(coupon==="WELCOME50"&&sub>=300)discount=50;if(coupon==="STUDENT15")discount=sub*.15}let taxable=Math.max(0,sub-discount),gst=taxable*.05;return{sub,discount,gst,total:taxable+gst,coupon}}
function cartHTML(){let c=cart();if(!c.length)return `<div class="empty-state"><h2>Your cart is empty.</h2><p>Add something delicious from our menu.</p><a class="btn btn-primary" href="menu.html">Explore Menu →</a></div>`;let t=totals();return `<div class="cart-items"><div class="section-head"><h2>Your items</h2><button class="small-btn danger" id="clearCart">Clear all</button></div>${c.map((x,i)=>`<div class="cart-item"><div class="mini-art">${x.emoji}</div><div><strong>${x.name}</strong><p class="muted">${money(x.price)} each</p><button class="remove-btn" data-remove="${x.id}">Remove</button></div><div class="qty-control"><button data-minus="${x.id}">−</button><strong>${x.qty}</strong><button data-plus="${x.id}">+</button></div><strong class="item-total">${money(x.price*x.qty)}</strong></div>`).join("")}</div><aside class="summary-card"><h2>Order summary</h2><div class="coupon-row"><input id="couponInput" placeholder="Coupon code" value="${t.coupon||""}"><button id="applyCoupon">Apply</button></div><div class="summary-row"><span>Subtotal</span><b>${money(t.sub)}</b></div><div class="summary-row"><span>Discount</span><b>− ${money(t.discount)}</b></div><div class="summary-row"><span>GST (5%)</span><b>${money(t.gst)}</b></div><div class="summary-total"><span>Total</span><span>${money(t.total)}</span></div><a class="btn btn-primary full-btn" href="checkout.html">Proceed to Checkout →</a></aside>`}
function renderCart(){let g=$("#cartPage");if(!g)return;g.innerHTML=cartHTML();$$("[data-remove]").forEach(b=>b.onclick=()=>{saveCart(cart().filter(x=>x.id!=b.dataset.remove));renderCart();toast("Item removed")});$$("[data-plus]").forEach(b=>b.onclick=()=>{let c=cart(),x=c.find(i=>i.id==b.dataset.plus);x.qty++;saveCart(c);renderCart()});$$("[data-minus]").forEach(b=>b.onclick=()=>{let c=cart(),x=c.find(i=>i.id==b.dataset.minus);x.qty--;if(x.qty<=0)c=c.filter(i=>i.id!=b.dataset.minus);saveCart(c);renderCart()});$("#clearCart")?.addEventListener("click",()=>{saveCart([]);renderCart()});$("#applyCoupon")?.addEventListener("click",()=>{let code=$("#couponInput").value.trim().toUpperCase(),valid=["BEAN10","WELCOME50","STUDENT15"];if(!valid.includes(code)){toast("Invalid coupon code");return}if(code==="WELCOME50"&&totals().sub<300){toast("WELCOME50 requires a ₹300 subtotal");return}set(COUPON_KEY,code);renderCart();toast("Coupon applied!")})}
function initCheckout(){let f=$("#checkoutForm");if(!f)return;if(!session()){location.href="login.html?return=checkout.html";return}if(!cart().length){location.href="menu.html";return}let u=session();$("#checkoutName").value=u.name||"";$("#checkoutEmail").value=u.email||"";$("#checkoutPhone").value=u.phone||"";function toggle(){let type=$("#orderType").value;$("#tableWrap").style.display=type==="Dine-In"?"flex":"none";$("#addressWrap").style.display=type==="Delivery"?"flex":"none";$("#address").required=type==="Delivery";$("#tableNumber").required=type==="Dine-In"}$("#orderType").onchange=toggle;toggle();let t=totals();$("#checkoutSummary").innerHTML=`<h2>Summary</h2>${cart().map(x=>`<div class="summary-row"><span>${x.name} × ${x.qty}</span><b>${money(x.price*x.qty)}</b></div>`).join("")}<div class="summary-row"><span>Discount</span><b>− ${money(t.discount)}</b></div><div class="summary-row"><span>GST</span><b>${money(t.gst)}</b></div><div class="summary-total"><span>Total</span><span>${money(t.total)}</span></div>`;f.onsubmit=e=>{e.preventDefault();let data={name:$("#checkoutName").value.trim(),phone:$("#checkoutPhone").value.trim(),email:$("#checkoutEmail").value.trim(),type:$("#orderType").value,table:$("#tableNumber").value,address:$("#address").value,payment:$('input[name="payment"]:checked').value};if(!/^[0-9]{10}$/.test(data.phone)){toast("Enter a valid 10-digit phone number");return}let now=new Date(),id="BB"+now.getFullYear()+String(now.getMonth()+1).padStart(2,"0")+String(now.getDate()).padStart(2,"0")+Math.floor(1000+Math.random()*9000),order={id,date:now.toISOString(),customer:data,items:cart(),...t,status:"Pending"};let os=get(ORDERS_KEY,[]);os.unshift(order);set(ORDERS_KEY,os);saveCart([]);localStorage.removeItem(COUPON_KEY);sessionStorage.setItem("lastOrder",id);location.href="orders.html?success=1"}}
function renderOrders(){let g=$("#ordersPage");if(!g)return;let u=session();if(!u){g.innerHTML=`<div class="empty-state"><h2>Login to see your orders.</h2><a class="btn btn-primary" href="login.html">Login →</a></div>`;return}let os=get(ORDERS_KEY,[]).filter(o=>o.customer.email===u.email);if(!os.length){g.innerHTML=`<div class="empty-state"><h2>No orders yet.</h2><p>Your next coffee adventure is waiting.</p><a class="btn btn-primary" href="menu.html">Order Now →</a></div>`;return}g.innerHTML=os.map(o=>{let statuses=["Pending","Confirmed","Preparing","Ready","Completed"],idx=statuses.indexOf(o.status);return `<article class="order-card"><div class="order-top"><div><span class="eyebrow">${new Date(o.date).toLocaleString("en-IN")}</span><div class="order-id">${o.id}</div></div><span class="status-pill ${o.status==="Completed"?"completed":""}">${o.status}</span></div><div class="order-items">${o.items.map(i=>`<span class="order-item-tag">${i.name} × ${i.qty}</span>`).join("")}</div><div class="progress">${statuses.map((s,i)=>`<div class="step ${i<=idx?"done":""}"><i>${i<=idx?"✓":i+1}</i><span>${s}</span></div>`).join("")}</div><div class="summary-row"><span>${o.customer.type} · ${o.customer.payment}</span><b>${money(o.total)}</b></div><button class="small-btn" data-reorder="${o.id}">Reorder</button></article>`}).join("");$$("[data-reorder]").forEach(b=>b.onclick=()=>{let o=os.find(x=>x.id===b.dataset.reorder),c=cart();o.items.forEach(i=>{let x=c.find(z=>z.id===i.id);if(x)x.qty+=i.qty;else c.push({...i})});saveCart(c);location.href="cart.html"})}
function initContact(){$("#contactForm")?.addEventListener("submit",e=>{e.preventDefault();e.target.reset();toast("Thanks! Your message has been sent.")})}
function initAuth(){users();$("#loginForm")?.addEventListener("submit",e=>{e.preventDefault();let email=$("#loginEmail").value.trim().toLowerCase(),pass=$("#loginPassword").value,u=users().find(x=>x.email===email&&x.password===pass);if(email==="admin@beanbliss.com"&&pass==="admin123")u={name:"Administrator",email,role:"admin"};if(!u){toast("Incorrect email or password");return}set(SESSION_KEY,u);if($("#remember").checked)localStorage.setItem("bb_remember","1");location.href=u.role==="admin"?"admin.html":"index.html"});$("#registerForm")?.addEventListener("submit",e=>{e.preventDefault();let name=$("#regName").value.trim(),email=$("#regEmail").value.trim().toLowerCase(),phone=$("#regPhone").value.trim(),pass=$("#regPassword").value,confirm=$("#regConfirm").value;if(pass!==confirm){toast("Passwords do not match");return}let u=users();if(u.some(x=>x.email===email)){toast("An account with this email already exists");return}u.push({name,email,phone,password:pass,role:"customer"});set(USERS_KEY,u);toast("Account created successfully");setTimeout(()=>location.href="login.html",700)});$$(".password-toggle").forEach(b=>b.onclick=()=>{let i=$("#"+b.dataset.target);i.type=i.type==="password"?"text":"password";b.textContent=i.type==="password"?"Show":"Hide"})}
function initAdmin(){let u=session();if(!u||u.role!=="admin"){location.href="login.html";return}let os=get(ORDERS_KEY,[]),us=users(),fs=foods(),revenue=os.reduce((a,o)=>a+o.total,0),pending=os.filter(o=>o.status!=="Completed"&&o.status!=="Cancelled").length,done=os.filter(o=>o.status==="Completed").length;$("#adminStats").innerHTML=[["Total Orders",os.length],["Customers",us.filter(x=>x.role!=="admin").length],["Revenue",money(revenue)],["Pending",pending],["Completed",done]].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");$("#adminFoods").innerHTML=fs.map(f=>`<div class="admin-row"><div><strong>${f.name}</strong><p>${f.cat} · ${money(f.price)} · ★ ${f.rating}</p></div><div class="admin-actions"><button class="small-btn" data-edit="${f.id}">Edit</button><button class="small-btn danger" data-delete="${f.id}">Delete</button></div></div>`).join("");$$("[data-delete]").forEach(b=>b.onclick=()=>{if(confirm("Delete this food item?")){set(FOOD_KEY,foods().filter(f=>f.id!=b.dataset.delete));initAdmin();toast("Food deleted")}});$$("[data-edit]").forEach(b=>b.onclick=()=>openFoodModal(foods().find(f=>f.id==b.dataset.edit)));$("#adminOrders").innerHTML=os.length?os.slice(0,20).map(o=>`<div class="admin-row"><div><strong>${o.id}</strong><p>${o.customer.name} · ${money(o.total)} · ${new Date(o.date).toLocaleDateString("en-IN")}</p></div><select class="status-select" data-status="${o.id}">${["Pending","Confirmed","Preparing","Ready","Completed","Cancelled"].map(s=>`<option ${o.status===s?"selected":""}>${s}</option>`).join("")}</select></div>`).join(""):`<p class="muted">No orders yet.</p>`;$$("[data-status]").forEach(s=>s.onchange=()=>{let all=get(ORDERS_KEY,[]),o=all.find(x=>x.id===s.dataset.status);if(o){o.status=s.value;set(ORDERS_KEY,all);toast("Order status updated");initAdmin()}});$("#adminCustomers").innerHTML=`<table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Orders</th></tr></thead><tbody>${us.filter(x=>x.role!=="admin").map(x=>`<tr><td>${x.name}</td><td>${x.email}</td><td>${x.phone}</td><td>${os.filter(o=>o.customer.email===x.email).length}</td></tr>`).join("")}</tbody></table>`}
function openFoodModal(f=null){let m=$("#adminModal");m.classList.remove("hidden");$("#foodModalTitle").textContent=f?"Edit food":"Add food";$("#foodId").value=f?.id||"";$("#foodName").value=f?.name||"";$("#foodCategory").value=f?.cat||"Coffee";$("#foodPrice").value=f?.price||"";$("#foodRating").value=f?.rating||4.5;$("#foodDescription").value=f?.desc||"";$("#foodVeg").checked=f?f.veg:true;$("#foodPopular").checked=f?.popular||false}
function initAdminEvents(){$("#addFoodBtn")?.addEventListener("click",()=>openFoodModal());$("#adminModalClose")?.addEventListener("click",()=>$("#adminModal").classList.add("hidden"));$("#foodForm")?.addEventListener("submit",e=>{e.preventDefault();let fs=foods(),id=Number($("#foodId").value)||Date.now(),old=fs.find(x=>x.id===id),f={id,name:$("#foodName").value.trim(),cat:$("#foodCategory").value,price:Number($("#foodPrice").value),rating:Number($("#foodRating").value),veg:$("#foodVeg").checked,popular:$("#foodPopular").checked,emoji:old?.emoji||"☕",desc:$("#foodDescription").value.trim(),ingredients:old?.ingredients||"Fresh ingredients"};let i=fs.findIndex(x=>x.id===id);if(i>=0)fs[i]=f;else fs.push(f);set(FOOD_KEY,fs);$("#adminModal").classList.add("hidden");initAdmin();toast("Food saved")});$("#adminLogout")?.addEventListener("click",()=>{localStorage.removeItem(SESSION_KEY);location.href="login.html"})}
function boot(){foods();users();updateCartCount();setupUserUI();setupTheme();setupNav();renderFeatured();initMenu();renderCart();initCheckout();renderOrders();initContact();initAuth();if($("#adminStats")){initAdmin();initAdminEvents()}if(location.search.includes("success=1"))toast("Order placed successfully!");}
document.addEventListener("DOMContentLoaded",boot);